train:
    dataset_class: datasets.neus_dataset.Dataset
    model_class: model.duplicate.DupNeuSRenderer

    loss_class: model.loss.NeuSLoss
    illum_loss_class: model.loss.NeuSVisLoss
    mat_loss_class: model.loss.NeuSMatLoss
    transformation_loss_class: model.loss.PointTransformationLoss

    ckpt_freq: 2000

    geo_plot_freq: 2500          # iterations
    vis_plot_freq: 500
    mat_plot_freq: 1000

    geo_num_pixels: 2048
    vis_num_pixels: 1024
    mat_num_pixels: 2048
    
    neus_learning_rate: 1e-4 
    neus_iter: 100000
    anneal_end: 0
    validate_resolution_level: 1
    warm_up_end: 5000
    learning_rate_alpha: 0.05

    illum_learning_rate: 2e-5
    illum_iter: 3001

    sg_learning_rate: 2e-4 
    sg_iter: 10000

    progressive_training: True


loss:
    eikonal_weight: 0.1
    mask_weight: 0.5
    normal_weight: 5
    loss_type: L2


illum_loss:
    loss_type: L1

mat_loss:
    sg_rgb_weight: 1.0
    kl_weight: 0.01
    latent_smooth_weight: 0.1 
    loss_type: L1

transformation_loss:
    instance_seg_weight: 50
    sdf_supervision_weight: 10

model:
    feature_vector_size: 256 
    use_siren_vis: True

    use_numerical_gradient: False
    use_colmap_constraint: False
    use_hessian: False
    use_triplane: False
    use_hash: False
    train_pose: False

    n_samples: 32
    n_importance: 32
    n_outside: 0
    up_sample_steps: 4  
    perturb: 1.0
    weight_threshold: 0.01

    variance_network:
        init_val: 0.3

    implicit_network:
        d_in: 3 
        dims: [ 512, 512, 512, 512, 512, 512, 512, 512 ]
        geometric_init: True
        bias: 0.6
        skip_in: [4]
        weight_norm: True
        multires: 6

    rendering_network:
        d_out: 3
        dims: [ 512, 512, 512, 512 ]
        weight_norm: True
        multires_view: 4
        
    visibility_network:
        dims: [ 256, 256, 256, 256 ]

    envmap_material_network:
        multires: 10
        brdf_encoder_dims: [ 512, 512, 512, 512 ]
        brdf_decoder_dims: [ 128, 128 ]
        num_lgt_sgs: 128
        upper_hemi: False
        specular_albedo: 0.02
        latent_dim: 64
        metallic_range: [0, 0]

    ray_tracer:
        object_bounding_sphere: 1.0
        sdf_threshold: 5.0e-5
        line_search_step: 0.5
        line_step_iters: 3
        sphere_tracing_iters: 5
        n_steps: 25
        n_rootfind_steps: 16

    transformation_network_regress:
        h_dim: 96
        n_layers: 8
        multires: 6